version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: